metadata_path: C:\Users\aksel\Documents\Code\ethograph\speed.npz
colors_sel: None
features_sel: speed
individuals_sel: individual_0
speed_columns_sel: mouse1
speed_columns_sel_previous: mouse2
trials_sel: 1
audiotrace_visible: true
ephys_visible: true
featureplot_visible: true
files_aligned_to_trials: true
labels_visible: true
neo_visible: true
pose_markers_visible: true
spectrogram_visible: true
video_viewer_visible: true
feature_view_mode: LinePlot
space_plot_type: Layers
ephys_offset: 0.0
