"""Syllable and trial counts per bird in the cross-validation benchmark.

Reads the ``labels_path`` of every session in ``crow{1,2,3}.yaml`` under
:data:`ROOT`, concatenates each bird's four label TSVs into one table and
counts its syllables (rows) and unique trials. Trial ids restart per session,
so a trial is a (session, trial) pair. Prints the counts and writes them to
``README.md`` in :data:`ROOT`.

    python scripts/paper1/crossval_label_counts.py
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import yaml

ROOT = Path(r"C:\Users\aksel\Documents\Code\ethograph\projects\paper\crossval_birds")
BIRDS = ("crow1", "crow2", "crow3")


def load_bird_labels(config: Path) -> pd.DataFrame:
    """Every session's labels of one bird config, tagged with its session."""
    sessions = yaml.safe_load(config.read_text())["sessions"]
    frames = []
    for session in sessions:
        path = Path(session["labels_path"])
        df = pd.read_csv(path, sep="\t")
        df["session"] = path.stem
        frames.append(df)
    return pd.concat(frames, ignore_index=True)


def count(df: pd.DataFrame) -> dict[str, int]:
    return {
        "sessions": df["session"].nunique(),
        "syllables": len(df),
        "trials": len(df[["session", "trial"]].drop_duplicates()),
    }


def to_markdown(counts: dict[str, dict[str, int]]) -> str:
    lines = [
        "# Cross-validation birds",
        "",
        "Labels per bird, from the `labels_path` of each session in `crow{1,2,3}.yaml`.",
        "A syllable is one row of the labels TSV; a trial is a unique (session, trial) pair.",
        "Generated by `scripts/paper1/crossval_label_counts.py`.",
        "",
        "| Bird | Sessions | Syllables | Trials |",
        "|------|---------:|----------:|-------:|",
    ]
    for bird, c in counts.items():
        lines.append(f"| {bird} | {c['sessions']} | {c['syllables']} | {c['trials']} |")
    total = {k: sum(c[k] for c in counts.values()) for k in ("sessions", "syllables", "trials")}
    lines.append(f"| **Total** | {total['sessions']} | {total['syllables']} | {total['trials']} |")
    return "\n".join(lines) + "\n"


def main() -> None:
    counts = {bird: count(load_bird_labels(ROOT / f"{bird}.yaml")) for bird in BIRDS}
    for bird, c in counts.items():
        print(f"{bird}: {c['syllables']} syllables, {c['trials']} trials ({c['sessions']} sessions)")
    readme = ROOT / "README.md"
    readme.write_text(to_markdown(counts))
    print(f"Wrote {readme}")


if __name__ == "__main__":
    main()
