apply_changepoint_correction: false
audiotrace_visible: true
av_speed_coupled: true
ava_use_softmax_amp: true
downsample_enabled: false
ephys_visible: true
featureplot_visible: true
filter_warnings: false
import_labels_nc_data: true
labels_visible: true
noise_reduce_enabled: false
pose_markers_visible: true
save_tsv_enabled: false
show_changepoints: true
skip_frames: false
spectrogram_visible: true
video_viewer_visible: true
energy_metric: energy_lowpass
feature_view_mode: LinePlot
heatmap_colormap: RdBu_r
heatmap_normalization: per_channel
space_plot_type: Layers
spec_colormap: CET-R4
spec_levels_mode: auto
audio_cp_hop_length_ms: 5.0
audio_cp_min_level_db: -70.0
audio_cp_min_syllable_length_s: 0.02
audio_cp_silence_threshold: 0.1
audio_playback_speed: 1.0
ava_max_freq: 110000.0
ava_min_freq: 30000.0
ava_smoothing_timescale: 0.007
band_env_max: 6000.0
band_env_min: 300.0
band_env_rate: 1000.0
buffer_multiplier: 5.0
downsample_factor: 100
env_cutoff: 500.0
env_rate: 2000.0
fps_playback: 30.0
fr_bin_size: 0.01
fr_sigma: 2.0
freq_cutoffs_max: 10000.0
freq_cutoffs_min: 500.0
heatmap_exclusion_percentile: 98.0
hop_frac: 0.5
nfft: 256
percentile_ylim: 99.5
pose_hide_threshold: 0.9
smooth_win: 2.0
time_jump_ms: 100.0
vmax_db: -25.3
vmin_db: -93.0
window_size: 5.0
