label_ids:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
- 21
- 22
- 23
- 24
- 25
- 26
- 27
- 50
names:
- background
- pullOutStick
- diagonalToBox
- toss
- swoop
- reachLeftCorner
- right
- pullOutAlongWall
- swoopOut
- stickToDisp
- stickInDisp
- lookToPellet
- snapPellet
- eat
- reachRightCorner
- nodding
- beakToDisp
- stickInDispTwo
- loseStick
- pickUpStick
- shake
- shiftRight
- shiftLeft
- pullOutLeft
- swoopOutLeft
- lookgToFallingPellet
- postNod
- reachRightCornerInTwo
- stimulation
