fs: 200.0000000000398
names:
- rate|rate_columns=93
- rate|rate_columns=97
- rate|rate_columns=102
- rate|rate_columns=103
- rate|rate_columns=136
- rate|rate_columns=140
- rate|rate_columns=144
- rate|rate_columns=146
- rate|rate_columns=148
- rate|rate_columns=182
- rate|rate_columns=188
- rate|rate_columns=190
- rate|rate_columns=196
- rate|rate_columns=214
- rate|rate_columns=297
- rate|rate_columns=303
- rate|rate_columns=311
- rate|rate_columns=315
features:
- rate
- rate
- rate
- rate
- rate
- rate
- rate
- rate
- rate
- rate
- rate
- rate
- rate
- rate
- rate
- rate
- rate
- rate
normalise:
- true
- true
- true
- true
- true
- true
- true
- true
- true
- true
- true
- true
- true
- true
- true
- true
- true
- true
vector_groups: []
kinds:
- neural_feature
- neural_feature
- neural_feature
- neural_feature
- neural_feature
- neural_feature
- neural_feature
- neural_feature
- neural_feature
- neural_feature
- neural_feature
- neural_feature
- neural_feature
- neural_feature
- neural_feature
- neural_feature
- neural_feature
- neural_feature
neural_columns:
  rate:
    rate_columns:
    - '93'
    - '97'
    - '102'
    - '103'
    - '136'
    - '140'
    - '144'
    - '146'
    - '148'
    - '182'
    - '188'
    - '190'
    - '196'
    - '214'
    - '297'
    - '303'
    - '311'
    - '315'
